products = [
    {
        '_id': '1',
        'name': 'Animal Planet - Alimento Cachorro Raza Pequeña',
        'image': '/images/aliperro.jpg',
        'description': 'La combinación de ingredientes esenciales formulado en este producto fortalece el sistema inmunológico, neuronal y músculo-esquelético, entre otros, permitiendo un crecimiento y desarrollo óptimo.',
        'brand': 'Animal Planet',
        'category': 'Alimento',
        'subcategory': 'Seco',
        'price': 15700,
        'countInStock': 10,
        'rating': 4.5,
        'numReviews': 12,
        'species': 'Perro',
        'format': '2,5 kg',
    },
    {
        '_id': '2',
        'name': 'Felix - Alimento Húmedo Gato Adulto Pollo e Hígado Sobre',
        'image': '/images/aligato.jpg',
        'description': 'Delicioso alimento húmedo completo y balanceado para gatos adultos, compuesto por trocitos de pollo e hígado, para deleitar hasta al paladar gatuno más exigente. Alimento 100% completo y balanceado.',
        'brand': 'Felix',
        'category': 'Alimento',
        'subcategory': 'Húmedo',
        'price': 900,
        'countInStock': 30,
        'rating': 3,
        'numReviews': 10,
        'species': 'Gato',
        'format': '85 gr',
    },
    {
        '_id': '3',
        'name': 'Afp - Juguete para Perro Doggies Pantufla Conejo',
        'image': '/images/pantuflas.jpg',
        'description': 'Con nuestros Doggies Pantuflas, pretendemos salvar tus zapatos, dándole unas pantuflas a tu perro para que juegue con ella.',
        'brand': 'AFP',
        'category': 'Juguete',
        'subcategory': '',
        'price': 12900,
        'countInStock': 0,
        'rating': 5,
        'numReviews': 20,
        'species': 'Perro',
        'format': 'Unidad',
    },
]
